# Generated by Django 6.0.4 on 2026-05-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eisauto', '0002_alter_location_google_maps_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='google_maps_url',
            field=models.URLField(help_text='Direct Google Maps link. Opens when user clicks button.'),
        ),
    ]
