# Generated by Django 6.0.4 on 2026-05-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eisauto', '0004_alter_location_google_maps_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='logo',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
