# Generated by Django 6.0.4 on 2026-05-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eisauto', '0005_remove_sitesettings_logo_sitesettings_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='homehero',
            name='title_second',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
