# Generated by Django 6.0.4 on 2026-05-20 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eisauto', '0006_homehero_title_second'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homehero',
            name='primary_button_link',
        ),
    ]
