# Generated by Django 6.0.4 on 2026-05-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eisauto', '0007_remove_homehero_primary_button_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='working_hours_text',
            field=models.CharField(blank=True, default='ВСЕКИ ДЕН', max_length=100),
        ),
    ]
