# Generated by Django 6.0.4 on 2026-05-21 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eisauto', '0009_homebenefit_icon_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
