# Generated by Django 6.0.4 on 2026-05-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eisauto', '0012_location_google_maps_embed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='google_maps_embed',
            field=models.TextField(blank=True, help_text='Постави Google Maps embed кода тук. Как: отвори Google Maps → намери мястото → бутон „Сподели(Share) → раздел „Вграждане на картакопирай HTML и го постави цял тук. Може да поставиш и само линка от „Сподели → Копирай линк'),
        ),
    ]
