# Generated by Django 6.0.4 on 2026-05-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eisauto', '0013_alter_location_google_maps_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='google_maps_url',
            field=models.URLField(default=1, help_text='Direct Google Maps link. Opens when user clicks button.', max_length=1000),
            preserve_default=False,
        ),
    ]
