# Generated by Django 6.0.4 on 2026-06-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eisauto', '0020_gallerypagesettings_show_stats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeBenefit',
        ),
        migrations.AlterField(
            model_name='gallerypagesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Снимката на колата вдясно в hero секцията.', null=True, upload_to='gallery/hero/', verbose_name='Hero снимка'),
        ),
        migrations.AlterField(
            model_name='gallerypagesettings',
            name='stat1_icon',
            field=models.CharField(default='bi-tools', help_text='Bootstrap icon клас', max_length=60, verbose_name='Иконка 1'),
        ),
    ]
