# Generated by Django 6.0.4 on 2026-06-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eisauto', '0025_remove_aboutpage_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='description',
            field=models.TextField(help_text='Основният текст. Може да използвате празен ред за нов параграф.', verbose_name='Описание на компанията'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='eyebrow',
            field=models.CharField(blank=True, default='За нас', max_length=80, verbose_name='Надпис над заглавието'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='founded_year',
            field=models.CharField(blank=True, help_text='Напр.: 2010', max_length=10, verbose_name='Година на основаване'),
        ),
    ]
