# Generated by Django 6.0.4 on 2026-06-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eisauto', '0026_alter_aboutpage_description_alter_aboutpage_eyebrow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='eyebrow',
            field=models.CharField(blank=True, max_length=80, verbose_name='Надпис над заглавието'),
        ),
    ]
