# Generated by Django 6.0.4 on 2026-06-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eisauto', '0028_servicepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicepage',
            options={'ordering': ['order'], 'verbose_name': 'Страница услуга', 'verbose_name_plural': 'Страници услуги'},
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Заглавие'),
        ),
    ]
