# Generated by Django 6.0.4 on 2026-09-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eisauto', '0030_merge_0029s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='service_type',
            field=models.CharField(choices=[('autoservice', 'Автосервиз'), ('transport', 'Пътна помощ'), ('tires', 'Гумаджийница')], max_length=20, unique=True, verbose_name='Тип услуга'),
        ),
    ]
