# Generated by Django 6.0.4 on 2026-09-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eisauto', '0031_alter_servicepage_service_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'Страница Контакти', 'verbose_name_plural': 'Страница Контакти'},
        ),
        migrations.AlterModelOptions(
            name='gallerypagesettings',
            options={'verbose_name': 'Снимка на Галерия най-отгоре', 'verbose_name_plural': 'Снимка на Галерия най-отгоре'},
        ),
        migrations.AlterModelOptions(
            name='homehero',
            options={'verbose_name': 'Основна секция - Начална страница', 'verbose_name_plural': 'Основна секция - Начална страница'},
        ),
        migrations.AlterModelOptions(
            name='homepromo',
            options={'verbose_name': 'Промоции - начална страница', 'verbose_name_plural': 'Промоции - начална страница'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': 'Услуги', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Настройки на сайта', 'verbose_name_plural': 'Настройки на сайта'},
        ),
    ]
