# Generated by Django 6.0.4 on 2026-09-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eisauto', '0032_alter_aboutpage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Снимки/Видео Галерия', 'verbose_name_plural': 'Снимки/Видео Галерия'},
        ),
        migrations.AlterModelOptions(
            name='gallerypagesettings',
            options={'verbose_name': 'Hero Настройки на Галерия', 'verbose_name_plural': 'Hero Настройки на Галерия'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['order'], 'verbose_name': 'Локация панел начална страница', 'verbose_name_plural': 'Локация панел начална страница'},
        ),
    ]
