# Generated by Django 6.0.4 on 2026-09-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eisauto', '0033_alter_galleryitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'Страница За Нас', 'verbose_name_plural': 'Страница За Нас'},
        ),
    ]
